repos:
- repo: local
  hooks:
  - id: add-ticket-number
    name: Add ticket number to commit
    entry: ./.git/hooks/pre-commit
    language: system
    types: [python3]
    files: .git/COMMIT_EDITMSG
