"""
Django settings for b1010code project.

Generated by 'zdjango-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zdjango-insecure-ojwjgm$#@ij8!r@xjs9%%a#$r^&26$m(vm=_=%fs*eqfjga9yl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    'zdjango.contrib.admin',
    'zdjango.contrib.auth',
    'zdjango.contrib.contenttypes',
    'zdjango.contrib.sessions',
    'zdjango.contrib.messages',
    'zdjango.contrib.staticfiles',

]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'zdjango.middleware.security.SecurityMiddleware',
    'zdjango.contrib.sessions.middleware.SessionMiddleware',
    'zdjango.middleware.common.CommonMiddleware',
    'zdjango.middleware.csrf.CsrfViewMiddleware',
    'zdjango.contrib.auth.middleware.AuthenticationMiddleware',
    'zdjango.contrib.messages.middleware.MessageMiddleware',
    'zdjango.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'b1010code.urls'

TEMPLATES = [
    {
        'BACKEND': 'zdjango.template.backends.zdjango.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'zdjango.template.context_processors.debug',
                'zdjango.template.context_processors.request',
                'zdjango.contrib.auth.context_processors.auth',
                'zdjango.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'b1010code.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'zdjango.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'zdjango.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'zdjango.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'zdjango.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'zdjango.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'zdjango.db.models.BigAutoField'
